[paths]
git_repo = "/mnt/seagate/recursos/copyfax"
pack_local = "/mnt/seagate/symlinks/kde-user-icons/copyfax"
pack_stable = "/mnt/seagate/recursos/copyfax/copyfax"
substitutes = "/mnt/seagate/symlinks/copydb/originais-descompactados/Fluent"

[environment]
env_root = "/mnt/seagate/workspace/coding/projetos/scripts/copykit/environments/copyfax"
mappings = "{ENVIRONMENT}/mappings"
readme_template = "{ENVIRONMENT}/README.md"